name: Scheduled Repo Announcement to Nostr

on:
  schedule:
    - cron: "0 12 * * 1"  # Every Monday at 12:00 UTC
  workflow_dispatch:

jobs:
  announce-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate announcement JSON
        uses: nostr-actions/generate-repo-announcement@v1
        with:
          output-path: .repo-announcement.json

      - name: Post to Nostr
        uses: nostr-actions/nostr-post-event@v1
        with:
          nostr-private-key: ${{ secrets.NOSTR_PRIVATE_KEY }}
          nostr-relay-url: wss://relay.damus.io
          github-event-name: "repository"
          github-event-path: ".repo-announcement.json"
