name: Post GitHub Events to Nostr

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, reopened, closed]
  discussion:
    types: [created]
  push:
    branches: [main]

jobs:
  post-to-nostr:
    runs-on: ubuntu-latest

    steps:
      - name: Use Nostr Post Event Action
        uses: your-org/nostr-post-event@v1
        with:
          nostr-private-key: ${{ secrets.NOSTR_PRIVATE_KEY }}
          nostr-relay-url: wss://relay.damus.io
