packages:
  - packages/*
  - packages/actions/*

onlyBuiltDependencies:
  - esbuild
  - svelte-preprocess

overrides:
  '@nostr-git/ui': link:packages/ui
  '@nostr-git/core': link:packages/core
  '@nostr-git/git-wrapper': link:packages/git-wrapper
  '@nostr-git/shared-types': link:packages/shared-types
