name: "Generate Nostr Repo Announcement"
description: "Fetches GitHub repo metadata and generates .repo-announcement.json for kind: 30617"
author: "your-org"
branding:
  icon: "book"
  color: "blue"

inputs:
  output-path:
    description: "Where to save the generated repo announcement JSON"
    required: false
    default: ".repo-announcement.json"

outputs:
  json-path:
    description: "Path to the generated JSON file"
    value: ${{ inputs.output-path }}

runs:
  using: "composite"
  steps:
    - name: Generate repo announcement
      shell: bash
      run: ./entrypoint.sh "${{ inputs.output-path }}"
